version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: egresados
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Docker/mysql_data:/var/lib/mysql  # Bind mount for persistent MySQL data
      - ./Docker/db_egresados:/docker-entrypoint-init.d/  # Custom initialization scripts
    ports:
      - '5000:3306'
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./Docker/mongo_data:/data/db
      - ./Docker/db_mongo:/docker-entrypoint-initdb.d/
    ports:
      - '27017:27017'

volumes:
  mysql_data:
  mongo_data:


# docker-compose up --build -d

