version: '3.8'

services:  
  mysql:
    build: .
    container_name: egresados
    environment:
      MYSQL_ROOT_PASSWORD : root
    volumes:
      - ./db_egresados:/docker-entrypoint-init.d/
    ports:
      - '5000:3306'

#docker-compose up --build
