version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: egresados
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./Docker/mysql_data:/var/lib/mysql  # Bind mount for persistent MySQL data
      - ./Docker/db_egresados:/docker-entrypoint-init.d/  # Custom initialization scripts
    ports:
      - '5000:3306'

volumes:
  mysql_data:


# docker-compose up --build -d

