services:
  mysql:
    image: mysql:latest
    container_name: egresados-db
    command:
      - --mysql-native-password=ON
      - --log-error-verbosity=3
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5000:3306"

volumes:
  mysql_data:
# docker-compose up --build -d
